Wed Dec 10 15:16:53 WIB 2025

diff --git a/auxel/makes b/auxel/makes
--- a/auxel/makes
+++ b/auxel/makes
@@ -242,7 +242,6 @@ function raptor_cores_prep_mulibs() {
 
 function raptor_cores_prep_pacmir() {
     test -e $pack_pacman && pacstrap /mnt - < $pack_pacman
-    
     if [ $? -ne 0 ]; then
         echo "Error: raptor package installation failed." >&2
         exit 1
@@ -252,6 +251,10 @@ function raptor_cores_prep_pacmir() {
 function craine_cores_post_config() {
     genfstab -U /mnt > /mnt/etc/fstab &&
     cp -fr $buildconf/* /mnt
+    if [ $? -ne 0 ]; then
+        echo "Error: raptor configuration installation failed." >&2
+        exit 1
+    fi
 }
 
 function raptor_cores_prep() {
