Wed Dec 10 15:14:53 WIB 2025

diff --git a/auxel/makes b/auxel/makes
--- a/auxel/makes
+++ b/auxel/makes
@@ -242,6 +242,11 @@ function raptor_cores_prep_mulibs() {
 
 function raptor_cores_prep_pacmir() {
     test -e $pack_pacman && pacstrap /mnt - < $pack_pacman
+    
+    if [ $? -ne 0 ]; then
+        echo "Error: raptor package installation failed." >&2
+        exit 1
+    fi
 }
 
 function craine_cores_post_config() {
